AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  inputNumber:
    Type: Number

Resources:
  CoolResource:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CoolNumber
      Type: String
      Value: !Ref CoolNumber
